# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_NAMESPACE: jamestalmage
  DOCKER_REPO_NAME: proxmox-auto-install-assistant

jobs:
  push_to_registry:
    name: Push ${{ matrix.base-image.image-tag }} image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        base-image:
          - image-name: debian:12.9-slim
            image-tag: debian-12.9-slim
            add-latest: true
          - image-name: node:22-bookworm
            image-tag: node-22-bookworm
            add-latest: false

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          flavor: |
            suffix=-${{ matrix.base-image.image-tag }},onlatest=true
          images: ${{env.DOCKER_NAMESPACE}}/${{env.DOCKER_REPO_NAME}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base-image.image-name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ matrix.base-image.add-latest }} && "latest"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_NAMESPACE}}/${{env.DOCKER_REPO_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  push_readme:
    name: Push README to Dockerhub
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{env.DOCKER_NAMESPACE}}/${{env.DOCKER_REPO_NAME}}
          provider: dockerhub
          short_description: ${{ github.event.repository.description }}
          readme_file: 'README.md'
